# Generated by Django 3.1.7 on 2021-04-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0002_air_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='id_airmensaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
