# Generated by Django 3.1.7 on 2021-04-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0003_auto_20210415_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_mensaje',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='asunto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
