# Generated by Django 3.1.7 on 2021-04-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0004_auto_20210415_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_mensaje',
            name='direccion_destino',
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='direccion_destino',
            field=models.ManyToManyField(to='amhsnacional.Usuario_ezpin'),
        ),
        migrations.RemoveField(
            model_name='air_mensaje',
            name='grupo_destino',
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='grupo_destino',
            field=models.ManyToManyField(to='amhsnacional.Grupo_ezpin'),
        ),
    ]
