# Generated by Django 3.1.7 on 2021-04-15 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0005_auto_20210415_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='hora_enviado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
