# Generated by Django 3.1.7 on 2021-04-15 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0006_auto_20210415_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_mensaje',
            name='adjunto',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='hora_visto',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
