# Generated by Django 3.1.7 on 2021-04-15 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0007_auto_20210415_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='adjunto',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='hora_enviado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='hora_visto',
            field=models.DateTimeField(blank=True),
        ),
    ]
