# Generated by Django 3.1.7 on 2021-04-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0011_auto_20210415_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('prioridad', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-prioridad'],
            },
        ),
        migrations.RemoveField(
            model_name='air_mensaje',
            name='asunto',
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='pioridad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='amhsnacional.prioridad'),
            preserve_default=False,
        ),
    ]
