# Generated by Django 3.1.7 on 2021-04-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0012_auto_20210415_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_mensaje',
            old_name='pioridad',
            new_name='prioridad',
        ),
    ]
