# Generated by Django 3.1.7 on 2021-04-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0013_auto_20210415_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id_direct', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='directorio_user', serialize=False, to='amhsnacional.usuario_ezpin')),
                ('dependencia', models.ManyToManyField(to='amhsnacional.Usuario_ezpin')),
                ('grupo', models.ManyToManyField(to='amhsnacional.Grupo_ezpin')),
            ],
            options={
                'ordering': ['-id_direct'],
            },
        ),
    ]
