# Generated by Django 3.1.7 on 2021-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0015_auto_20210415_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_ezpin',
            options={'ordering': ['-nombre_grupo']},
        ),
        migrations.RemoveField(
            model_name='grupo_ezpin',
            name='id_grupo',
        ),
        migrations.AddField(
            model_name='grupo_ezpin',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
