# Generated by Django 3.1.7 on 2021-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0016_auto_20210415_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_ezpin',
            options={'ordering': ['-id_grupo']},
        ),
        migrations.RemoveField(
            model_name='grupo_ezpin',
            name='id',
        ),
        migrations.AddField(
            model_name='grupo_ezpin',
            name='id_grupo',
            field=models.AutoField(default=2345, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
