# Generated by Django 3.1.7 on 2021-04-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0017_auto_20210415_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorio',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='directorio',
            name='id_direct',
        ),
        migrations.RemoveField(
            model_name='grupo_ezpin',
            name='integrantes',
        ),
        migrations.DeleteModel(
            name='Air_mensaje',
        ),
        migrations.DeleteModel(
            name='Directorio',
        ),
        migrations.DeleteModel(
            name='Grupo_ezpin',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.DeleteModel(
            name='Usuario_ezpin',
        ),
    ]
