# Generated by Django 3.1.7 on 2021-04-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0019_air_mensaje_directorio_grupo_ezpin_prioridad_usuario_ezpin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorio',
            options={'ordering': ['-id_directorio']},
        ),
        migrations.RenameField(
            model_name='directorio',
            old_name='id_direct',
            new_name='id_directorio',
        ),
    ]
