# Generated by Django 3.1.7 on 2021-04-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0020_auto_20210415_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_mensaje',
            name='origen',
            field=models.OneToOneField(default=98765, on_delete=django.db.models.deletion.PROTECT, related_name='origen_msj', to='amhsnacional.usuario_ezpin'),
            preserve_default=False,
        ),
    ]
