# Generated by Django 3.1.7 on 2021-04-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0021_air_mensaje_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_mensaje',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='air_mensaje',
            name='guardado',
            field=models.BooleanField(default=False),
        ),
    ]
