# Generated by Django 3.1.7 on 2021-04-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0024_auto_20210415_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_mensaje',
            old_name='dependencia_destin',
            new_name='dependencia_destino',
        ),
    ]
