# Generated by Django 3.1.7 on 2021-04-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0025_auto_20210415_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen_msj', to='amhsnacional.usuario_ezpin'),
        ),
    ]
