# Generated by Django 3.1.7 on 2021-04-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0026_auto_20210415_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorio',
            name='dependencia',
        ),
    ]
