# Generated by Django 3.1.7 on 2021-04-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0027_remove_directorio_dependencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorio',
            options={'ordering': ['-directorio_usuario']},
        ),
        migrations.RenameField(
            model_name='directorio',
            old_name='id_directorio',
            new_name='directorio_usuario',
        ),
        migrations.AddField(
            model_name='usuario_ezpin',
            name='icao_amhs',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='archivado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='dependencia_destino',
            field=models.ManyToManyField(blank=True, to='amhsnacional.Usuario_ezpin'),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='eliminado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='enviado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='guardado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
