# Generated by Django 3.1.7 on 2021-04-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0027_remove_directorio_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_ezpin',
            name='icao_amhs',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
