# Generated by Django 3.1.7 on 2021-04-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0028_usuario_ezpin_icao_amhs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_ezpin',
            name='icao_amhs',
        ),
    ]
