# Generated by Django 3.1.7 on 2021-04-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0030_usuario_ezpin_icao_amhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='dependencia_destino',
            field=models.ManyToManyField(blank=True, null=True, to='amhsnacional.Usuario_ezpin'),
        ),
    ]
