# Generated by Django 3.1.7 on 2021-04-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0031_auto_20210422_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='dependencia_destino',
            field=models.ManyToManyField(blank=True, to='amhsnacional.Usuario_ezpin'),
        ),
    ]
