# Generated by Django 3.1.7 on 2021-04-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0032_auto_20210422_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_ezpin',
            name='icao_amhs',
        ),
    ]
