# Generated by Django 3.1.7 on 2021-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amhsnacional', '0033_remove_usuario_ezpin_icao_amhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_mensaje',
            name='archivado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='eliminado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='enviado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='air_mensaje',
            name='guardado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
